/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainGUI.java
 *
 * Created on 16.08.2009, 17:34:21
 */
package de.twentyhills.picmov;

import com.jidesoft.hints.FileIntelliHints;
import com.jidesoft.swing.SelectAllUtils;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author ntrs
 */
public class MainGUI extends javax.swing.JFrame {

    /** Creates new form MainGUI */
    public MainGUI() {
        try {
            // Set System L&F
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            //UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
        } catch (UnsupportedLookAndFeelException e) {
            // handle exception
        } catch (ClassNotFoundException e) {
            // handle exception
        } catch (InstantiationException e) {
            // handle exception
        } catch (IllegalAccessException e) {
            // handle exception
        }

        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        heading = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        center = new de.twentyhills.util.gui.LinearGradientPanel();
        sourceFolderLabel = new javax.swing.JLabel();
        stepOneLabel = new javax.swing.JLabel();
        source_folder_textfield = new javax.swing.JTextField();
        source_folder_button = new javax.swing.JButton();
        stepTwoLabel = new javax.swing.JLabel();
        targetFolderLabel = new javax.swing.JLabel();
        target_folder_textfield = new javax.swing.JTextField();
        target_folder_button = new javax.swing.JButton();
        start_button = new javax.swing.JButton();
        stop_button = new javax.swing.JButton();
        example_label_top = new javax.swing.JLabel();
        example_label_bottom = new javax.swing.JLabel();
        bottom = new de.twentyhills.util.gui.LinearGradientPanel();
        progress_label = new javax.swing.JLabel();
        progress_bar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("de/twentyhills/picmov/Bundle"); // NOI18N
        setTitle(bundle.getString("MainGUI.title")); // NOI18N
        setName("mainFrame"); // NOI18N

        content.setName("basePanel"); // NOI18N
        content.setPreferredSize(new java.awt.Dimension(520, 520));
        content.setLayout(new java.awt.BorderLayout());

        heading.setBackground(new java.awt.Color(210, 180, 140));
        heading.setName("heading"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(bundle.getString("MainGUI.jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(bundle.getString("MainGUI.jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        javax.swing.GroupLayout headingLayout = new javax.swing.GroupLayout(heading);
        heading.setLayout(headingLayout);
        headingLayout.setHorizontalGroup(
            headingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE))
                .addContainerGap())
        );
        headingLayout.setVerticalGroup(
            headingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        content.add(heading, java.awt.BorderLayout.PAGE_START);

        center.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        center.setName("center"); // NOI18N

        sourceFolderLabel.setFont(center.getFont());
        sourceFolderLabel.setText(bundle.getString("MainGUI.sourceFolderLabel.text")); // NOI18N
        sourceFolderLabel.setMaximumSize(new java.awt.Dimension(100, 14));
        sourceFolderLabel.setMinimumSize(new java.awt.Dimension(100, 14));
        sourceFolderLabel.setName("sourceFolderLabel"); // NOI18N
        sourceFolderLabel.setPreferredSize(new java.awt.Dimension(100, 14));

        stepOneLabel.setFont(center.getFont());
        stepOneLabel.setText(bundle.getString("MainGUI.stepOneLabel.text")); // NOI18N
        stepOneLabel.setName("stepOneLabel"); // NOI18N

        source_folder_textfield.setFont(center.getFont());
        source_folder_textfield.setName("source_folder_textfield"); // NOI18N

        source_folder_button.setFont(center.getFont());
        source_folder_button.setText(bundle.getString("MainGUI.source_folder_button.text")); // NOI18N
        source_folder_button.setName("source_folder_button"); // NOI18N

        stepTwoLabel.setFont(center.getFont());
        stepTwoLabel.setText(bundle.getString("MainGUI.stepTwoLabel.text")); // NOI18N
        stepTwoLabel.setName("stepTwoLabel"); // NOI18N

        targetFolderLabel.setFont(center.getFont());
        targetFolderLabel.setText(bundle.getString("MainGUI.targetFolderLabel.text")); // NOI18N
        targetFolderLabel.setMaximumSize(new java.awt.Dimension(100, 14));
        targetFolderLabel.setMinimumSize(new java.awt.Dimension(100, 14));
        targetFolderLabel.setName("targetFolderLabel"); // NOI18N
        targetFolderLabel.setPreferredSize(new java.awt.Dimension(100, 14));

        target_folder_textfield.setFont(center.getFont());
        target_folder_textfield.setName("target_folder_textfield"); // NOI18N

        target_folder_button.setFont(center.getFont());
        target_folder_button.setText(bundle.getString("MainGUI.target_folder_button.text")); // NOI18N
        target_folder_button.setName("target_folder_button"); // NOI18N

        start_button.setFont(center.getFont());
        start_button.setText(bundle.getString("MainGUI.start_button.text")); // NOI18N
        start_button.setName("start_button"); // NOI18N
        start_button.setPreferredSize(new java.awt.Dimension(75, 23));

        stop_button.setFont(center.getFont());
        stop_button.setText(bundle.getString("MainGUI.stop_button.text")); // NOI18N
        stop_button.setName("stop_button"); // NOI18N

        example_label_top.setFont(center.getFont());
        example_label_top.setText(bundle.getString("MainGUI.example_label_top.text")); // NOI18N
        example_label_top.setName("example_label_top"); // NOI18N

        example_label_bottom.setFont(center.getFont());
        example_label_bottom.setText(bundle.getString("MainGUI.example_label_bottom.text")); // NOI18N
        example_label_bottom.setName("example_label_bottom"); // NOI18N

        javax.swing.GroupLayout centerLayout = new javax.swing.GroupLayout(center);
        center.setLayout(centerLayout);
        centerLayout.setHorizontalGroup(
            centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerLayout.createSequentialGroup()
                .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, centerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(stepOneLabel)
                        .addGap(410, 410, 410))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, centerLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, centerLayout.createSequentialGroup()
                                .addComponent(source_folder_textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(source_folder_button))
                            .addComponent(sourceFolderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, centerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stepTwoLabel)
                            .addGroup(centerLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, centerLayout.createSequentialGroup()
                                        .addComponent(target_folder_textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(target_folder_button))
                                    .addComponent(targetFolderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)))))
                    .addGroup(centerLayout.createSequentialGroup()
                        .addContainerGap(400, Short.MAX_VALUE)
                        .addComponent(start_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stop_button))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, centerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(example_label_bottom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                            .addComponent(example_label_top, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE))))
                .addContainerGap())
        );

        centerLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {start_button, stop_button});

        centerLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {source_folder_button, target_folder_button});

        centerLayout.setVerticalGroup(
            centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stepOneLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sourceFolderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(source_folder_button)
                    .addComponent(source_folder_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(stepTwoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(targetFolderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(target_folder_button)
                    .addComponent(target_folder_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(example_label_top)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(example_label_bottom)
                .addGap(18, 18, 18)
                .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(start_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stop_button))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        centerLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {example_label_bottom, example_label_top});

        SelectAllUtils.install(source_folder_textfield);
        FileIntelliHints fileIntelliHints = new FileIntelliHints(source_folder_textfield);
        fileIntelliHints.setFolderOnly(true);
        fileIntelliHints.setFollowCaret(true);
        fileIntelliHints.setShowFullPath(false);
        SelectAllUtils.install(target_folder_textfield);
        FileIntelliHints targetFileIntelliHints = new FileIntelliHints(target_folder_textfield);
        targetFileIntelliHints.setFolderOnly(true);
        targetFileIntelliHints.setFollowCaret(true);
        targetFileIntelliHints.setShowFullPath(false);

        content.add(center, java.awt.BorderLayout.CENTER);

        bottom.setEndColor(new java.awt.Color(238, 238, 238));
        bottom.setName("bottom"); // NOI18N
        bottom.setStartColor(new java.awt.Color(153, 170, 170));

        progress_label.setText(bundle.getString("MainGUI.progress_label.text")); // NOI18N
        progress_label.setName("progress_label"); // NOI18N

        progress_bar.setName("progress_bar"); // NOI18N

        javax.swing.GroupLayout bottomLayout = new javax.swing.GroupLayout(bottom);
        bottom.setLayout(bottomLayout);
        bottomLayout.setHorizontalGroup(
            bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(progress_bar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                    .addComponent(progress_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE))
                .addContainerGap())
        );
        bottomLayout.setVerticalGroup(
            bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(progress_label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(progress_bar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        content.add(bottom, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private de.twentyhills.util.gui.LinearGradientPanel bottom;
    private javax.swing.JPanel center;
    private javax.swing.JPanel content;
    private javax.swing.JLabel example_label_bottom;
    private javax.swing.JLabel example_label_top;
    private javax.swing.JPanel heading;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JProgressBar progress_bar;
    private javax.swing.JLabel progress_label;
    private javax.swing.JLabel sourceFolderLabel;
    private javax.swing.JButton source_folder_button;
    private javax.swing.JTextField source_folder_textfield;
    private javax.swing.JButton start_button;
    private javax.swing.JLabel stepOneLabel;
    private javax.swing.JLabel stepTwoLabel;
    private javax.swing.JButton stop_button;
    private javax.swing.JLabel targetFolderLabel;
    private javax.swing.JButton target_folder_button;
    private javax.swing.JTextField target_folder_textfield;
    // End of variables declaration//GEN-END:variables
}
